=== Adding a new column

Version of the app: `2.0.0.NEWCOLUMN`

Version of the DB: `v2newcolumn`

==== Comment

===== Rolling a new version

Steps:

. migrate your db to create the new column called `age`. Now your db is in `v2newcolumn`
. write the code to use the new column. Now your app is in version `2.0.0.NEWCOLUMN`

If you're using Spring Boot Flyway those two steps will be performed upon booting the version `2.0.0.NEWCOLUMN` of the app.
If you're running database versioning tool manually then you'd have to do it in separate processes
(first manually upgrade the db version and then deploy the new app).

===== A/B testing

The current situation is that we have an app deployed to production in version `1.0.0` and db in `v1`. We want to deploy the second
instance of the app that will be in version `2.0.0.NEWCOLUMN` and update the db to `v2newcolumn`.

Steps:

. a new instance is deployed in version `2.0.0.NEWCOLUMN` that updates the db to `v2newcolumn`
. in the meantime some requests got processed by instances being in version `1.0.0`
. the upgrade is successful and you have some instances working in `1.0.0`, others in `2.0.0.NEWCOLUMN`. All are talking to db in `v2newcolumn`
. version `1.0.0` is not using the database's column `age` and version `2.0.0.NEWCOLUMN` is. They don't interfere each other, no exceptions
should be thrown.

===== Rolling back the application

The current situation is that we have app in version `2.0.0.NEWCOLUMN` and db in `v2newcolumn`.

Steps:

. roll back your app to version `1.0.0`.
. version `1.0.0` is not using the database's column `age` thus rollback should be successful

==== DB changes

The script adds a new column called `age`.

[source,sql,indent=0]
----
include::src/main/resources/db/migration/V2__Add_age.sql[]
----

==== Code changes

The app uses the new column. No breaking changes were introduced.

[source,java,indent=0]
----
include::src/main/java/sample/flyway/Person.java[]
----
